version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "23:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.codehaus.groovy:groovy
    versions:
    - ">= 3.a, < 4"
  - dependency-name: org.codehaus.groovy:groovy-json
    versions:
    - ">= 3.a, < 4"
  - dependency-name: org.codehaus.groovy:groovy-macro
    versions:
    - ">= 3.a, < 4"
  - dependency-name: org.codehaus.groovy:groovy-nio
    versions:
    - ">= 3.a, < 4"
  - dependency-name: org.codehaus.groovy:groovy-sql
    versions:
    - ">= 3.a, < 4"
  - dependency-name: org.codehaus.groovy:groovy-templates
    versions:
    - ">= 3.a, < 4"
  - dependency-name: org.codehaus.groovy:groovy-test
    versions:
    - ">= 3.a, < 4"
  - dependency-name: org.codehaus.groovy:groovy-xml
    versions:
    - ">= 3.a, < 4"
  - dependency-name: org.glassfish.hk2:guice-bridge
    versions:
    - "> 2.6.1"
  - dependency-name: ru.vyarus.mkdocs
    versions:
    - 2.1.0
    - 2.1.1
  - dependency-name: org.ow2.asm:asm
    versions:
    - "9.1"
  - dependency-name: ru.vyarus.quality
    versions:
    - 4.5.0
  - dependency-name: org.junit.platform:junit-platform-testkit
    versions:
    - 1.7.1
